### ISSUE TITLE
以默认配置编译运行，页面返回Forbiden，可能是啥原因呢，另外能否提供完整的hello demo，利于初学者入门，谢谢！

### ISSUE THREAD

**Issue by shawvi** [webcpp/httpevent#3]

**Comment by webcpp** [comment]
此项目已经升级为更为强大的hi-nginx,https://github.com/webcpp/hi-nginx，请更新关注。谢谢。hi-nginx配有demo和doc：
https://github.com/webcpp/hi_demo
https://github.com/webcpp/hi-nginx-doc
